// ============================================================
// UBG PRO — GAME LIBRARY
// 100+ games: iframes from CrazyGames, Poki, SilverGames,
// itch.io, simmer.io (Unity), and direct embeds
// ============================================================

const GAMES = [
  // ---- ACTION ----
  { id: 1,  name: "Stick Merge",        cat: "action",      emoji: "🗡️",  url: "https://www.crazygames.com/embed/stick-merge",              featured: true  },
  { id: 2,  name: "Bullet Force",       cat: "shooting",    emoji: "🔫",  url: "https://www.crazygames.com/embed/bullet-force-multiplayer", featured: true  },
  { id: 3,  name: "Venge.io",           cat: "shooting",    emoji: "🎯",  url: "https://venge.io/",                                        featured: false },
  { id: 4,  name: "Shell Shockers",     cat: "shooting",    emoji: "🥚",  url: "https://shellshock.io/",                                   featured: true  },
  { id: 5,  name: "1v1.LOL",            cat: "shooting",    emoji: "🏗️",  url: "https://1v1.lol/",                                         featured: true  },
  { id: 6,  name: "Warbrokers.io",      cat: "shooting",    emoji: "⚔️",  url: "https://warbrokers.io/",                                   featured: false },
  { id: 7,  name: "Krunker.io",         cat: "shooting",    emoji: "🔫",  url: "https://krunker.io/",                                      featured: true  },
  { id: 8,  name: "Forward Assault",    cat: "shooting",    emoji: "💣",  url: "https://www.crazygames.com/embed/forward-assault-remix",    featured: false },
  { id: 9,  name: "Pixel Combat 2",     cat: "shooting",    emoji: "👾",  url: "https://www.crazygames.com/embed/pixel-combat-2",           featured: false },
  { id: 10, name: "Combat Reloaded",    cat: "shooting",    emoji: "🎖️",  url: "https://www.crazygames.com/embed/combat-reloaded",          featured: false },

  // ---- MULTIPLAYER ----
  { id: 11, name: "Slither.io",         cat: "multiplayer", emoji: "🐍",  url: "https://slither.io/",                                      featured: true  },
  { id: 12, name: "Agar.io",            cat: "multiplayer", emoji: "🔵",  url: "https://agar.io/",                                         featured: false },
  { id: 13, name: "Surviv.io",          cat: "multiplayer", emoji: "🏝️",  url: "https://surviv.io/",                                       featured: false },
  { id: 14, name: "Mope.io",            cat: "multiplayer", emoji: "🐾",  url: "https://mope.io/",                                         featured: false },
  { id: 15, name: "Diep.io",            cat: "multiplayer", emoji: "🪖",  url: "https://diep.io/",                                         featured: false },
  { id: 16, name: "Zombs Royale",       cat: "multiplayer", emoji: "🧟",  url: "https://zombsroyale.io/",                                  featured: true  },
  { id: 17, name: "Skribbl.io",         cat: "multiplayer", emoji: "🖌️",  url: "https://skribbl.io/",                                      featured: false },
  { id: 18, name: "Paper.io 2",         cat: "multiplayer", emoji: "📄",  url: "https://www.crazygames.com/embed/paper-io-2",               featured: false },
  { id: 19, name: "Wormate.io",         cat: "multiplayer", emoji: "🪱",  url: "https://wormate.io/",                                      featured: false },
  { id: 20, name: "Splix.io",           cat: "multiplayer", emoji: "🧩",  url: "https://splix.io/",                                        featured: false },

  // ---- RACING ----
  { id: 21, name: "Madalin Cars Multiplayer", cat: "racing", emoji: "🏎️", url: "https://www.crazygames.com/embed/madalin-cars-multiplayer", featured: true },
  { id: 22, name: "Road Fury",          cat: "racing",      emoji: "🚗",  url: "https://www.crazygames.com/embed/road-fury",                featured: false },
  { id: 23, name: "Moto X3M",           cat: "racing",      emoji: "🏍️",  url: "https://www.crazygames.com/embed/moto-x3m",                 featured: true  },
  { id: 24, name: "Moto X3M Winter",    cat: "racing",      emoji: "❄️",  url: "https://www.crazygames.com/embed/moto-x3m-winter",          featured: false },
  { id: 25, name: "Drift Boss",         cat: "racing",      emoji: "🌀",  url: "https://www.crazygames.com/embed/drift-boss",               featured: false },
  { id: 26, name: "Traffic Rider",      cat: "racing",      emoji: "🛵",  url: "https://www.crazygames.com/embed/traffic-rider",            featured: false },
  { id: 27, name: "Highway Racer",      cat: "racing",      emoji: "🛣️",  url: "https://www.crazygames.com/embed/highway-racer",            featured: false },
  { id: 28, name: "Car Rush",           cat: "racing",      emoji: "💨",  url: "https://www.crazygames.com/embed/car-rush",                 featured: false },
  { id: 29, name: "Neon Rider",         cat: "racing",      emoji: "🌈",  url: "https://www.crazygames.com/embed/neon-rider",               featured: false },

  // ---- PUZZLE ----
  { id: 30, name: "2048",               cat: "puzzle",      emoji: "🔢",  url: "https://www.crazygames.com/embed/2048",                     featured: false },
  { id: 31, name: "Cut the Rope",       cat: "puzzle",      emoji: "✂️",  url: "https://www.crazygames.com/embed/cut-the-rope-remastered",  featured: false },
  { id: 32, name: "Water Sort Puzzle",  cat: "puzzle",      emoji: "💧",  url: "https://www.crazygames.com/embed/water-sort-puzzle",        featured: false },
  { id: 33, name: "Bob the Robber",     cat: "puzzle",      emoji: "🕵️",  url: "https://www.crazygames.com/embed/bob-the-robber",           featured: false },
  { id: 34, name: "Jelly Doods",        cat: "puzzle",      emoji: "🍮",  url: "https://www.crazygames.com/embed/jelly-doods",              featured: false },
  { id: 35, name: "Find the Cat",       cat: "puzzle",      emoji: "🐱",  url: "https://www.crazygames.com/embed/find-the-cat",             featured: false },
  { id: 36, name: "Good Sudoku",        cat: "puzzle",      emoji: "🔢",  url: "https://www.crazygames.com/embed/good-sudoku",              featured: false },
  { id: 37, name: "Chess",              cat: "puzzle",      emoji: "♟️",  url: "https://www.chess.com/play/computer",                      featured: false },
  { id: 38, name: "Wordle",             cat: "puzzle",      emoji: "📝",  url: "https://www.nytimes.com/games/wordle/index.html",           featured: false },
  { id: 39, name: "Sugar Sugar",        cat: "puzzle",      emoji: "🍬",  url: "https://www.crazygames.com/embed/sugar-sugar-3",            featured: false },

  // ---- ADVENTURE ----
  { id: 40, name: "Run 3",              cat: "adventure",   emoji: "🏃",  url: "https://www.coolmathgames.com/0-run-3",                     featured: true  },
  { id: 41, name: "Fireboy Watergirl",  cat: "adventure",   emoji: "🔥",  url: "https://www.crazygames.com/embed/fireboy-and-watergirl-1-the-forest-temple", featured: false },
  { id: 42, name: "Tomb of the Cat",    cat: "adventure",   emoji: "🐱",  url: "https://www.crazygames.com/embed/tomb-of-the-cat",          featured: false },
  { id: 43, name: "Geometry Dash Lite", cat: "action",      emoji: "🔷",  url: "https://www.crazygames.com/embed/geometry-dash",            featured: false },
  { id: 44, name: "Temple Run 2",       cat: "adventure",   emoji: "🏛️",  url: "https://poki.com/en/g/temple-run-2",                       featured: false },
  { id: 45, name: "Stickman Hook",      cat: "adventure",   emoji: "🕸️",  url: "https://www.crazygames.com/embed/stickman-hook",            featured: false },
  { id: 46, name: "Bob the Robber 4",   cat: "adventure",   emoji: "🔦",  url: "https://www.crazygames.com/embed/bob-the-robber-4",         featured: false },
  { id: 47, name: "Minecraft Classic",  cat: "adventure",   emoji: "⛏️",  url: "https://classic.minecraft.net/",                           featured: true  },

  // ---- SPORTS ----
  { id: 48, name: "Basketball Stars",   cat: "sports",      emoji: "🏀",  url: "https://www.crazygames.com/embed/basketball-stars",         featured: false },
  { id: 49, name: "Soccer Skills World Cup", cat: "sports", emoji: "⚽", url: "https://www.crazygames.com/embed/soccer-skills-world-cup",   featured: false },
  { id: 50, name: "Tennis Clash",       cat: "sports",      emoji: "🎾",  url: "https://www.crazygames.com/embed/tennis-clash-3d",          featured: false },
  { id: 51, name: "Rooftop Snipers",    cat: "sports",      emoji: "🏹",  url: "https://www.crazygames.com/embed/rooftop-snipers",          featured: false },
  { id: 52, name: "Football Legends",   cat: "sports",      emoji: "🏈",  url: "https://www.crazygames.com/embed/football-legends",         featured: false },
  { id: 53, name: "Golf Battle",        cat: "sports",      emoji: "⛳",  url: "https://www.crazygames.com/embed/golf-battle",              featured: false },
  { id: 54, name: "8 Ball Pool",        cat: "sports",      emoji: "🎱",  url: "https://www.crazygames.com/embed/8-ball-pool",              featured: false },

  // ---- STRATEGY ----
  { id: 55, name: "Bloons TD 5",        cat: "strategy",    emoji: "🎈",  url: "https://www.crazygames.com/embed/bloons-tower-defense-5",   featured: false },
  { id: 56, name: "Kingdom Rush",       cat: "strategy",    emoji: "🏰",  url: "https://www.crazygames.com/embed/kingdom-rush",             featured: false },
  { id: 57, name: "Clash of Clans",     cat: "strategy",    emoji: "⚔️",  url: "https://www.crazygames.com/embed/mini-royale-nations",      featured: false },
  { id: 58, name: "Warzone Commander",  cat: "strategy",    emoji: "🗺️",  url: "https://www.crazygames.com/embed/warzone-commander",        featured: false },
  { id: 59, name: "Mini Royale",        cat: "strategy",    emoji: "👑",  url: "https://miniroyale.io/",                                   featured: false },
  { id: 60, name: "Tiny Fishing",       cat: "strategy",    emoji: "🎣",  url: "https://www.crazygames.com/embed/tiny-fishing",             featured: false },

  // ---- UNITY GAMES ----
  { id: 61, name: "Dino Squad",         cat: "unity",       emoji: "🦕",  url: "https://simmer.io/@simmer/dino-squad",                     featured: false, unity: true },
  { id: 62, name: "Smash Karts",        cat: "unity",       emoji: "🏎️",  url: "https://smashkarts.io/",                                   featured: true,  unity: true },
  { id: 63, name: "Bonk.io",            cat: "unity",       emoji: "💥",  url: "https://bonk.io/",                                         featured: false, unity: true },
  { id: 64, name: "Narrow.One",         cat: "unity",       emoji: "🏹",  url: "https://narrow.one/",                                      featured: true,  unity: true },
  { id: 65, name: "Getaway Shootout",   cat: "unity",       emoji: "🚁",  url: "https://www.crazygames.com/embed/getaway-shootout",         featured: false, unity: true },
  { id: 66, name: "Ragdoll Archers",    cat: "unity",       emoji: "🎯",  url: "https://www.crazygames.com/embed/ragdoll-archers",          featured: false, unity: true },
  { id: 67, name: "Slope",              cat: "action",      emoji: "⛷️",  url: "https://slope-game.github.io/",                            featured: true  },
  { id: 68, name: "Uno Online",         cat: "multiplayer", emoji: "🃏",  url: "https://www.crazygames.com/embed/uno-online",               featured: false, unity: true },
  { id: 69, name: "Tribals.io",         cat: "unity",       emoji: "🏕️",  url: "https://tribals.io/",                                      featured: false, unity: true },
  { id: 70, name: "GoBattle.io",        cat: "unity",       emoji: "⚔️",  url: "https://gobattle.io/",                                     featured: false, unity: true },
  { id: 71, name: "Town of Salem",      cat: "unity",       emoji: "🕵️",  url: "https://www.blankmediagames.com/TownOfSalem/",              featured: false, unity: true },
  { id: 72, name: "Lost Ruins",         cat: "unity",       emoji: "🏚️",  url: "https://simmer.io/@simmer/lost-ruins",                     featured: false, unity: true },

  // ---- MORE ACTION ----
  { id: 73, name: "Knife Hit",          cat: "action",      emoji: "🔪",  url: "https://www.crazygames.com/embed/knife-hit",                featured: false },
  { id: 74, name: "Stickman Fighter",   cat: "action",      emoji: "🥊",  url: "https://www.crazygames.com/embed/stickman-fighter-epic-battle", featured: false },
  { id: 75, name: "Iron Snout",         cat: "action",      emoji: "🐷",  url: "https://www.crazygames.com/embed/iron-snout",               featured: false },
  { id: 76, name: "Banjo Kazooie",      cat: "action",      emoji: "🎸",  url: "https://www.crazygames.com/embed/stickman-hook",            featured: false },
  { id: 77, name: "Raze 3",             cat: "action",      emoji: "🚀",  url: "https://www.crazygames.com/embed/raze",                     featured: false },
  { id: 78, name: "Super Smash Flash 2",cat: "action",      emoji: "👊",  url: "https://www.supersmashflash.com/",                         featured: true  },
  { id: 79, name: "Masked Forces",      cat: "shooting",    emoji: "😷",  url: "https://www.crazygames.com/embed/masked-forces",            featured: false },
  { id: 80, name: "House of Hazards",   cat: "multiplayer", emoji: "🏠",  url: "https://www.crazygames.com/embed/house-of-hazards",         featured: false },
  { id: 81, name: "Stickman Army",      cat: "action",      emoji: "💂",  url: "https://www.crazygames.com/embed/stickman-army-team-battle",featured: false },
  { id: 82, name: "Crossy Road",        cat: "adventure",   emoji: "🐓",  url: "https://www.crazygames.com/embed/crossy-road",              featured: false },
  { id: 83, name: "Duck Life 4",        cat: "adventure",   emoji: "🦆",  url: "https://www.crazygames.com/embed/duck-life-4",              featured: false },
  { id: 84, name: "Learn to Fly 3",     cat: "action",      emoji: "🐧",  url: "https://www.crazygames.com/embed/learn-to-fly-3",           featured: false },
  { id: 85, name: "Doodle Jump",        cat: "action",      emoji: "📱",  url: "https://www.crazygames.com/embed/doodle-jump",              featured: false },
  { id: 86, name: "Subway Surfers",     cat: "action",      emoji: "🚇",  url: "https://www.crazygames.com/embed/subway-surfers",           featured: true  },
  { id: 87, name: "Stick War Legacy",   cat: "strategy",    emoji: "🗡️",  url: "https://www.crazygames.com/embed/stick-war-legacy",         featured: false },
  { id: 88, name: "Sniper 3D",          cat: "shooting",    emoji: "🎯",  url: "https://www.crazygames.com/embed/sniper-3d",                featured: false },
  { id: 89, name: "Idle Breakout",      cat: "strategy",    emoji: "⬛",  url: "https://www.crazygames.com/embed/idle-breakout",            featured: false },
  { id: 90, name: "Cookie Clicker",     cat: "strategy",    emoji: "🍪",  url: "https://orteil.dashnet.org/cookieclicker/",                 featured: false },
  { id: 91, name: "Drive Mad",          cat: "racing",      emoji: "🚙",  url: "https://www.crazygames.com/embed/drive-mad",                featured: false },
  { id: 92, name: "Tank Trouble",       cat: "action",      emoji: "🪖",  url: "https://www.crazygames.com/embed/tank-trouble",             featured: false },
  { id: 93, name: "Stick Fight",        cat: "action",      emoji: "🧍",  url: "https://www.crazygames.com/embed/stick-duel-medieval-wars", featured: false },
  { id: 94, name: "Fall Guys Knockouts",cat: "multiplayer", emoji: "👾",  url: "https://www.crazygames.com/embed/stumble-guys",             featured: false },
  { id: 95, name: "Eggy Car",           cat: "racing",      emoji: "🥚",  url: "https://www.crazygames.com/embed/eggy-car",                 featured: false },
  { id: 96, name: "Retro Bowl",         cat: "sports",      emoji: "🏈",  url: "https://www.crazygames.com/embed/retro-bowl",               featured: true  },
  { id: 97, name: "Helix Jump",         cat: "action",      emoji: "🌀",  url: "https://www.crazygames.com/embed/helix-jump",               featured: false },
  { id: 98, name: "Raft Wars",          cat: "action",      emoji: "🚢",  url: "https://www.crazygames.com/embed/raft-wars-2",              featured: false },
  { id: 99, name: "Happy Wheels",       cat: "action",      emoji: "🚲",  url: "https://totaljerkface.com/happy_wheels.tjf",                featured: true  },
  { id: 100, name: "Backflip Dive",     cat: "sports",      emoji: "🤿",  url: "https://www.crazygames.com/embed/backflip-dive-3d",          featured: false },
  { id: 101, name: "Lordz.io",          cat: "strategy",    emoji: "👑",  url: "https://www.lordz.io/",                                    featured: false },
  { id: 102, name: "Fortnite Chapter 2",cat: "unity",       emoji: "🔫",  url: "https://www.crazygames.com/embed/fortnite-chapter-2",       featured: false, unity: true },
  { id: 103, name: "Among Us Online",   cat: "multiplayer", emoji: "🚀",  url: "https://www.crazygames.com/embed/among-us-online-edition",  featured: true  },
  { id: 104, name: "Clash of Armies",   cat: "strategy",    emoji: "⚔️",  url: "https://www.crazygames.com/embed/clash-of-armies",          featured: false },
  { id: 105, name: "Snake.io",          cat: "multiplayer", emoji: "🐍",  url: "https://www.crazygames.com/embed/snake-io",                 featured: false },
];
